name: Bienvenida!

on:
  push:
    branches:
      - main

jobs:
  saludo_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Saludar
        run: |
         echo "Hola Github Actions!!!"

      - name: Obtener fecha
        run: |
          echo date [-u|--utc|--universal] [MMDDhhmm[[CC]YY][.ss]]
          ls -l